name: navigator
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  transparent_image: ^1.0.0
  http: ^0.12.0+1
  flutter_secure_storage: 3.3.1+1
  logger: 0.8.3
  rxdart: ^0.23.0
  flutter_bloc: ^3.0.0
  progress_dialog: 1.2.0
  fluttertoast: ^3.1.3
  random_color: 1.0.3
  provider: ^4.0.1
  flutter_socket_io: ^0.6.0
  animations: 1.1.2

  zoom_widget: ^0.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: NanumBrushScript
      fonts:
        - asset: fonts/NanumBrushScript-Regular.ttf

