name: navigator
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  transparent_image: ^2.0.0-nullsafety.0
  http: ^0.13.0
  flutter_secure_storage: ^4.1.0
  logger: ^1.0.0-nullsafety.0
  rxdart: ^0.26.0
  flutter_bloc: ^7.0.0-nullsafety.5
  fluttertoast: ^8.0.1-nullsafety.0
  random_color: ^1.0.6-nullsafety
  provider: ^5.0.0
  animations: ^2.0.0
  flutter_svg: ^0.21.0-nullsafety.0
  intl: ^0.17.0
  get: ^4.0.0-nullsafety.2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: NanumBrushScript
      fonts:
        - asset: fonts/NanumBrushScript-Regular.ttf

